:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency:  25
:queues:
  - default
  - mailers
  - CUHappyCorner_production_mailers
  - CUHappyCorner_production_default
  - CUHappyCorner_production_CUHappyCorner_production_default