# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
TransactionType.create(id: "2ndhand", name: "2nd Hand Goods")
TransactionType.create(id: "system", name: "System")
TransactionType.create(id: "other", name: "Other")
Organization.create(org_identifier:"cucoop", name: "CU Coop", infinite_credit: true)
a = SecondHandGoodCategory.create(id: "01", name: "衣物")
b = SecondHandGoodCategory.create(id: "02", name: "袋類")
c = SecondHandGoodCategory.create(id: "03", name: "煮食用具")
d = SecondHandGoodCategory.create(id: "04", name: "餐具")
e = SecondHandGoodCategory.create(id: "05", name: "電器")
f = SecondHandGoodCategory.create(id: "06", name: "文具")
g = SecondHandGoodCategory.create(id: "07", name: "工具")
h = SecondHandGoodCategory.create(id: "08", name: "飾物")
i = SecondHandGoodCategory.create(id: "09", name: "體育用品")
j = SecondHandGoodCategory.create(id: "10", name: "小型家品")
k = SecondHandGoodCategory.create(id: "11", name: "小型擺設")
l = SecondHandGoodCategory.create(id: "12", name: "玩具／桌上遊戲")
m = SecondHandGoodCategory.create(id: "13", name: "樂器")
o = SecondHandGoodCategory.create(id: "14", name: "清潔用品")
p = SecondHandGoodCategory.create(id: "15", name: "化妝品、護膚品")
q = SecondHandGoodCategory.create(id: "16", name: "畢業公仔")
r = SecondHandGoodCategory.create(id: "17", name: "手工用品 Art Jam")

SecondHandGoodType.create(id:"01a", name: "短袖上衣", default_buying_price: 30 , default_selling_price:60 ,category: a )
SecondHandGoodType.create(id:"01b", name: "長袖上衣", default_buying_price: 40, default_selling_price: 80,category: a)
SecondHandGoodType.create(id:"01c", name: "長褲", default_buying_price: 60, default_selling_price: 120,category: a)
SecondHandGoodType.create(id:"01d", name: "短褲", default_buying_price: 50, default_selling_price: 100,category: a)
SecondHandGoodType.create(id:"01e", name: "連身裙", default_buying_price: 60, default_selling_price: 120,category: a)
SecondHandGoodType.create(id:"01f", name: "半截裙", default_buying_price: 50, default_selling_price: 100,category: a)
SecondHandGoodType.create(id:"01g", name: "外套", default_buying_price: 90, default_selling_price: 180,category: a)
SecondHandGoodType.create(id:"01h", name: "衣物配件：圍巾、帽、皮帶、襪、絲襪、leggings", 	default_buying_price: 25, default_selling_price: 50,category: a)
SecondHandGoodType.create(id:"01i", name: "中大衣物：PE衫", default_buying_price: 20, default_selling_price: 40,category: a)
SecondHandGoodType.create(id:"01j", name: "中大衣物：Lab coat", default_buying_price: 50, default_selling_price: 100,category: a)
SecondHandGoodType.create(id:"02a", name: "細袋 <16”", default_buying_price: 25, default_selling_price: 50,category: b)
SecondHandGoodType.create(id:"02b", name: "中袋 =16”", default_buying_price: 40, default_selling_price: 80,category: b)
SecondHandGoodType.create(id:"02c", name: "大袋 >16”", default_buying_price: 60, default_selling_price: 120,category: b)
SecondHandGoodType.create(id:"03a", name: "不用駁電：煲、煎pan", default_buying_price: 90, default_selling_price: 180,category: c)
SecondHandGoodType.create(id:"03b", name: "駁電：電飯煲、熱水煲、gas爐、電磁爐、瓦煲", default_buying_price: 125, default_selling_price: 250,category: c)
SecondHandGoodType.create(id:"04a", name: "餐具：筷子、刀、叉、匙", default_buying_price: 10, default_selling_price: 20,category: d)
SecondHandGoodType.create(id:"04b", name: "器皿：碗碟、食物盒、杯、水壺、新水樽", default_buying_price: 15, default_selling_price: 30,category: d)
SecondHandGoodType.create(id:"05a", name: "風筒、電腦、電話、遊戲機、打印機、音響、吸塵機、耳機、枱燈、雪櫃、碎紙機、燙斗", default_buying_price: 125, default_selling_price: 250,category: e)
SecondHandGoodType.create(id:"06a", name: "記事簿、文件夾、信封(1 pack)、信紙(1 pack)、筆筒、膠紙、memo紙、顏色筆、File (每5個)", default_buying_price: 10, default_selling_price: 20,category: f)
SecondHandGoodType.create(id:"06b", name: "計算機", default_buying_price: 90, default_selling_price: 180,category: f)
SecondHandGoodType.create(id:"07a", name: "維修、木工、測量", default_buying_price: 30, default_selling_price: 60,category: g)
SecondHandGoodType.create(id:"08a", name: "手鏈、頸鏈、耳環、頭飾、眼鏡框", default_buying_price: 25, default_selling_price: 50,category: h)
SecondHandGoodType.create(id:"09a", name: "球、球拍、健身器材、瑜珈墊、露營用品", default_buying_price: 60, default_selling_price: 120,category: i)
SecondHandGoodType.create(id:"10a", name: "置物盒、鞋架、洗衣籃、衣架(每10個)、面盆、晾衫繩、化妝袋", default_buying_price: 30, default_selling_price: 60,category: j)
SecondHandGoodType.create(id:"11a", name: "相架、模型、地球儀、水晶球、畫", default_buying_price: 25, default_selling_price: 50,category: k)
SecondHandGoodType.create(id:"12a", name: "大富翁、UNOS、麻雀、砌圖、lego、積木", default_buying_price: 30, default_selling_price: 60,category: l)
SecondHandGoodType.create(id:"13a", name: "樂器：吉他、電子琴、Ukulele、小提琴、鼓", default_buying_price: 120, default_selling_price: 240,category: m)
SecondHandGoodType.create(id:"13b", name: "小型樂器：笛、沙搥、響板、搖鼓、口琴、牧童笛", default_buying_price: 20, default_selling_price: 40,category: m)
SecondHandGoodType.create(id:"13c", name: "樂器配件：鼓棍、拍子機、音箱、咪", default_buying_price: 90, default_selling_price: 180,category: m)
SecondHandGoodType.create(id:"14a", name: "沐浴露、洗衣粉", default_buying_price: 30, default_selling_price: 60,category: o)
SecondHandGoodType.create(id:"15a", name: "指甲油、面膜", default_buying_price: 20, default_selling_price: 40,category: p)
SecondHandGoodType.create(id:"16a", name: "大", default_buying_price: 80, default_selling_price: 160,category: q)
SecondHandGoodType.create(id:"16b", name: "中", default_buying_price: 50, default_selling_price: 100 ,category: q)
SecondHandGoodType.create(id:"16c", name: "小", default_buying_price: 20, default_selling_price: 40,category: q)
SecondHandGoodType.create(id:"17a", name: "手工用品 Art Jam 各類", default_buying_price: 10 , default_selling_price:0 ,category: r)